// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cirq-landing-split/SplitScreen.tsx": () => import("../components/mockups/cirq-landing-split/SplitScreen.tsx")
};
